/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated.workspace'
import { Route as AuthenticatedJurisprudenciaRouteImport } from './routes/_authenticated.jurisprudencia'
import { Route as AuthenticatedHistoricoLoteRouteImport } from './routes/_authenticated.historico-lote'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCompartilhamentosRouteImport } from './routes/_authenticated.compartilhamentos'
import { Route as AuthenticatedCnjRouteImport } from './routes/_authenticated.cnj'
import { Route as AuthenticatedBibliotecariosRouteImport } from './routes/_authenticated.bibliotecarios'
import { Route as AuthenticatedAssistentesRouteImport } from './routes/_authenticated.assistentes'
import { Route as ApiPublicInventariaProcessContextRouteImport } from './routes/api/public/inventaria-process-context'
import { Route as ApiPublicAdvogaProcessContextRouteImport } from './routes/api/public/advoga-process-context'
import { Route as AuthenticatedPecasNovaRouteImport } from './routes/_authenticated.pecas.nova'
import { Route as AuthenticatedPecasIdRouteImport } from './routes/_authenticated.pecas.$id'
import { Route as AuthenticatedFerramentasLinksRouteImport } from './routes/_authenticated.ferramentas.links'
import { Route as AuthenticatedConfiguracoesSegurancaRouteImport } from './routes/_authenticated.configuracoes.seguranca'
import { Route as AuthenticatedConfiguracoesIdentidadeRouteImport } from './routes/_authenticated.configuracoes.identidade'
import { Route as AuthenticatedConfiguracoesIaRouteImport } from './routes/_authenticated.configuracoes.ia'
import { Route as AuthenticatedBibliotecaModelosRouteImport } from './routes/_authenticated.biblioteca.modelos'
import { Route as AuthenticatedAdminIntegracoesRouteImport } from './routes/_authenticated.admin.integracoes'
import { Route as AuthenticatedBibliotecaModelosIdRouteImport } from './routes/_authenticated.biblioteca.modelos.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJurisprudenciaRoute =
  AuthenticatedJurisprudenciaRouteImport.update({
    id: '/jurisprudencia',
    path: '/jurisprudencia',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoricoLoteRoute =
  AuthenticatedHistoricoLoteRouteImport.update({
    id: '/historico-lote',
    path: '/historico-lote',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompartilhamentosRoute =
  AuthenticatedCompartilhamentosRouteImport.update({
    id: '/compartilhamentos',
    path: '/compartilhamentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCnjRoute = AuthenticatedCnjRouteImport.update({
  id: '/cnj',
  path: '/cnj',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBibliotecariosRoute =
  AuthenticatedBibliotecariosRouteImport.update({
    id: '/bibliotecarios',
    path: '/bibliotecarios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssistentesRoute =
  AuthenticatedAssistentesRouteImport.update({
    id: '/assistentes',
    path: '/assistentes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicInventariaProcessContextRoute =
  ApiPublicInventariaProcessContextRouteImport.update({
    id: '/api/public/inventaria-process-context',
    path: '/api/public/inventaria-process-context',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdvogaProcessContextRoute =
  ApiPublicAdvogaProcessContextRouteImport.update({
    id: '/api/public/advoga-process-context',
    path: '/api/public/advoga-process-context',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPecasNovaRoute = AuthenticatedPecasNovaRouteImport.update({
  id: '/pecas/nova',
  path: '/pecas/nova',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPecasIdRoute = AuthenticatedPecasIdRouteImport.update({
  id: '/pecas/$id',
  path: '/pecas/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFerramentasLinksRoute =
  AuthenticatedFerramentasLinksRouteImport.update({
    id: '/ferramentas/links',
    path: '/ferramentas/links',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfiguracoesSegurancaRoute =
  AuthenticatedConfiguracoesSegurancaRouteImport.update({
    id: '/configuracoes/seguranca',
    path: '/configuracoes/seguranca',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfiguracoesIdentidadeRoute =
  AuthenticatedConfiguracoesIdentidadeRouteImport.update({
    id: '/configuracoes/identidade',
    path: '/configuracoes/identidade',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfiguracoesIaRoute =
  AuthenticatedConfiguracoesIaRouteImport.update({
    id: '/configuracoes/ia',
    path: '/configuracoes/ia',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBibliotecaModelosRoute =
  AuthenticatedBibliotecaModelosRouteImport.update({
    id: '/biblioteca/modelos',
    path: '/biblioteca/modelos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIntegracoesRoute =
  AuthenticatedAdminIntegracoesRouteImport.update({
    id: '/admin/integracoes',
    path: '/admin/integracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBibliotecaModelosIdRoute =
  AuthenticatedBibliotecaModelosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedBibliotecaModelosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/assistentes': typeof AuthenticatedAssistentesRoute
  '/bibliotecarios': typeof AuthenticatedBibliotecariosRoute
  '/cnj': typeof AuthenticatedCnjRoute
  '/compartilhamentos': typeof AuthenticatedCompartilhamentosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historico-lote': typeof AuthenticatedHistoricoLoteRoute
  '/jurisprudencia': typeof AuthenticatedJurisprudenciaRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/p/$slug': typeof PSlugRoute
  '/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/biblioteca/modelos': typeof AuthenticatedBibliotecaModelosRouteWithChildren
  '/configuracoes/ia': typeof AuthenticatedConfiguracoesIaRoute
  '/configuracoes/identidade': typeof AuthenticatedConfiguracoesIdentidadeRoute
  '/configuracoes/seguranca': typeof AuthenticatedConfiguracoesSegurancaRoute
  '/ferramentas/links': typeof AuthenticatedFerramentasLinksRoute
  '/pecas/$id': typeof AuthenticatedPecasIdRoute
  '/pecas/nova': typeof AuthenticatedPecasNovaRoute
  '/api/public/advoga-process-context': typeof ApiPublicAdvogaProcessContextRoute
  '/api/public/inventaria-process-context': typeof ApiPublicInventariaProcessContextRoute
  '/biblioteca/modelos/$id': typeof AuthenticatedBibliotecaModelosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/assistentes': typeof AuthenticatedAssistentesRoute
  '/bibliotecarios': typeof AuthenticatedBibliotecariosRoute
  '/cnj': typeof AuthenticatedCnjRoute
  '/compartilhamentos': typeof AuthenticatedCompartilhamentosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historico-lote': typeof AuthenticatedHistoricoLoteRoute
  '/jurisprudencia': typeof AuthenticatedJurisprudenciaRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/p/$slug': typeof PSlugRoute
  '/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/biblioteca/modelos': typeof AuthenticatedBibliotecaModelosRouteWithChildren
  '/configuracoes/ia': typeof AuthenticatedConfiguracoesIaRoute
  '/configuracoes/identidade': typeof AuthenticatedConfiguracoesIdentidadeRoute
  '/configuracoes/seguranca': typeof AuthenticatedConfiguracoesSegurancaRoute
  '/ferramentas/links': typeof AuthenticatedFerramentasLinksRoute
  '/pecas/$id': typeof AuthenticatedPecasIdRoute
  '/pecas/nova': typeof AuthenticatedPecasNovaRoute
  '/api/public/advoga-process-context': typeof ApiPublicAdvogaProcessContextRoute
  '/api/public/inventaria-process-context': typeof ApiPublicInventariaProcessContextRoute
  '/biblioteca/modelos/$id': typeof AuthenticatedBibliotecaModelosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/assistentes': typeof AuthenticatedAssistentesRoute
  '/_authenticated/bibliotecarios': typeof AuthenticatedBibliotecariosRoute
  '/_authenticated/cnj': typeof AuthenticatedCnjRoute
  '/_authenticated/compartilhamentos': typeof AuthenticatedCompartilhamentosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/historico-lote': typeof AuthenticatedHistoricoLoteRoute
  '/_authenticated/jurisprudencia': typeof AuthenticatedJurisprudenciaRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
  '/p/$slug': typeof PSlugRoute
  '/_authenticated/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/_authenticated/biblioteca/modelos': typeof AuthenticatedBibliotecaModelosRouteWithChildren
  '/_authenticated/configuracoes/ia': typeof AuthenticatedConfiguracoesIaRoute
  '/_authenticated/configuracoes/identidade': typeof AuthenticatedConfiguracoesIdentidadeRoute
  '/_authenticated/configuracoes/seguranca': typeof AuthenticatedConfiguracoesSegurancaRoute
  '/_authenticated/ferramentas/links': typeof AuthenticatedFerramentasLinksRoute
  '/_authenticated/pecas/$id': typeof AuthenticatedPecasIdRoute
  '/_authenticated/pecas/nova': typeof AuthenticatedPecasNovaRoute
  '/api/public/advoga-process-context': typeof ApiPublicAdvogaProcessContextRoute
  '/api/public/inventaria-process-context': typeof ApiPublicInventariaProcessContextRoute
  '/_authenticated/biblioteca/modelos/$id': typeof AuthenticatedBibliotecaModelosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/assistentes'
    | '/bibliotecarios'
    | '/cnj'
    | '/compartilhamentos'
    | '/dashboard'
    | '/historico-lote'
    | '/jurisprudencia'
    | '/workspace'
    | '/p/$slug'
    | '/admin/integracoes'
    | '/biblioteca/modelos'
    | '/configuracoes/ia'
    | '/configuracoes/identidade'
    | '/configuracoes/seguranca'
    | '/ferramentas/links'
    | '/pecas/$id'
    | '/pecas/nova'
    | '/api/public/advoga-process-context'
    | '/api/public/inventaria-process-context'
    | '/biblioteca/modelos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/assistentes'
    | '/bibliotecarios'
    | '/cnj'
    | '/compartilhamentos'
    | '/dashboard'
    | '/historico-lote'
    | '/jurisprudencia'
    | '/workspace'
    | '/p/$slug'
    | '/admin/integracoes'
    | '/biblioteca/modelos'
    | '/configuracoes/ia'
    | '/configuracoes/identidade'
    | '/configuracoes/seguranca'
    | '/ferramentas/links'
    | '/pecas/$id'
    | '/pecas/nova'
    | '/api/public/advoga-process-context'
    | '/api/public/inventaria-process-context'
    | '/biblioteca/modelos/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/_authenticated/assistentes'
    | '/_authenticated/bibliotecarios'
    | '/_authenticated/cnj'
    | '/_authenticated/compartilhamentos'
    | '/_authenticated/dashboard'
    | '/_authenticated/historico-lote'
    | '/_authenticated/jurisprudencia'
    | '/_authenticated/workspace'
    | '/p/$slug'
    | '/_authenticated/admin/integracoes'
    | '/_authenticated/biblioteca/modelos'
    | '/_authenticated/configuracoes/ia'
    | '/_authenticated/configuracoes/identidade'
    | '/_authenticated/configuracoes/seguranca'
    | '/_authenticated/ferramentas/links'
    | '/_authenticated/pecas/$id'
    | '/_authenticated/pecas/nova'
    | '/api/public/advoga-process-context'
    | '/api/public/inventaria-process-context'
    | '/_authenticated/biblioteca/modelos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PSlugRoute: typeof PSlugRoute
  ApiPublicAdvogaProcessContextRoute: typeof ApiPublicAdvogaProcessContextRoute
  ApiPublicInventariaProcessContextRoute: typeof ApiPublicInventariaProcessContextRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jurisprudencia': {
      id: '/_authenticated/jurisprudencia'
      path: '/jurisprudencia'
      fullPath: '/jurisprudencia'
      preLoaderRoute: typeof AuthenticatedJurisprudenciaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historico-lote': {
      id: '/_authenticated/historico-lote'
      path: '/historico-lote'
      fullPath: '/historico-lote'
      preLoaderRoute: typeof AuthenticatedHistoricoLoteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compartilhamentos': {
      id: '/_authenticated/compartilhamentos'
      path: '/compartilhamentos'
      fullPath: '/compartilhamentos'
      preLoaderRoute: typeof AuthenticatedCompartilhamentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cnj': {
      id: '/_authenticated/cnj'
      path: '/cnj'
      fullPath: '/cnj'
      preLoaderRoute: typeof AuthenticatedCnjRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bibliotecarios': {
      id: '/_authenticated/bibliotecarios'
      path: '/bibliotecarios'
      fullPath: '/bibliotecarios'
      preLoaderRoute: typeof AuthenticatedBibliotecariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assistentes': {
      id: '/_authenticated/assistentes'
      path: '/assistentes'
      fullPath: '/assistentes'
      preLoaderRoute: typeof AuthenticatedAssistentesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/inventaria-process-context': {
      id: '/api/public/inventaria-process-context'
      path: '/api/public/inventaria-process-context'
      fullPath: '/api/public/inventaria-process-context'
      preLoaderRoute: typeof ApiPublicInventariaProcessContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/advoga-process-context': {
      id: '/api/public/advoga-process-context'
      path: '/api/public/advoga-process-context'
      fullPath: '/api/public/advoga-process-context'
      preLoaderRoute: typeof ApiPublicAdvogaProcessContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pecas/nova': {
      id: '/_authenticated/pecas/nova'
      path: '/pecas/nova'
      fullPath: '/pecas/nova'
      preLoaderRoute: typeof AuthenticatedPecasNovaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pecas/$id': {
      id: '/_authenticated/pecas/$id'
      path: '/pecas/$id'
      fullPath: '/pecas/$id'
      preLoaderRoute: typeof AuthenticatedPecasIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ferramentas/links': {
      id: '/_authenticated/ferramentas/links'
      path: '/ferramentas/links'
      fullPath: '/ferramentas/links'
      preLoaderRoute: typeof AuthenticatedFerramentasLinksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes/seguranca': {
      id: '/_authenticated/configuracoes/seguranca'
      path: '/configuracoes/seguranca'
      fullPath: '/configuracoes/seguranca'
      preLoaderRoute: typeof AuthenticatedConfiguracoesSegurancaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes/identidade': {
      id: '/_authenticated/configuracoes/identidade'
      path: '/configuracoes/identidade'
      fullPath: '/configuracoes/identidade'
      preLoaderRoute: typeof AuthenticatedConfiguracoesIdentidadeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes/ia': {
      id: '/_authenticated/configuracoes/ia'
      path: '/configuracoes/ia'
      fullPath: '/configuracoes/ia'
      preLoaderRoute: typeof AuthenticatedConfiguracoesIaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/biblioteca/modelos': {
      id: '/_authenticated/biblioteca/modelos'
      path: '/biblioteca/modelos'
      fullPath: '/biblioteca/modelos'
      preLoaderRoute: typeof AuthenticatedBibliotecaModelosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/integracoes': {
      id: '/_authenticated/admin/integracoes'
      path: '/admin/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AuthenticatedAdminIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/biblioteca/modelos/$id': {
      id: '/_authenticated/biblioteca/modelos/$id'
      path: '/$id'
      fullPath: '/biblioteca/modelos/$id'
      preLoaderRoute: typeof AuthenticatedBibliotecaModelosIdRouteImport
      parentRoute: typeof AuthenticatedBibliotecaModelosRoute
    }
  }
}

interface AuthenticatedBibliotecaModelosRouteChildren {
  AuthenticatedBibliotecaModelosIdRoute: typeof AuthenticatedBibliotecaModelosIdRoute
}

const AuthenticatedBibliotecaModelosRouteChildren: AuthenticatedBibliotecaModelosRouteChildren =
  {
    AuthenticatedBibliotecaModelosIdRoute:
      AuthenticatedBibliotecaModelosIdRoute,
  }

const AuthenticatedBibliotecaModelosRouteWithChildren =
  AuthenticatedBibliotecaModelosRoute._addFileChildren(
    AuthenticatedBibliotecaModelosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAssistentesRoute: typeof AuthenticatedAssistentesRoute
  AuthenticatedBibliotecariosRoute: typeof AuthenticatedBibliotecariosRoute
  AuthenticatedCnjRoute: typeof AuthenticatedCnjRoute
  AuthenticatedCompartilhamentosRoute: typeof AuthenticatedCompartilhamentosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoricoLoteRoute: typeof AuthenticatedHistoricoLoteRoute
  AuthenticatedJurisprudenciaRoute: typeof AuthenticatedJurisprudenciaRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
  AuthenticatedAdminIntegracoesRoute: typeof AuthenticatedAdminIntegracoesRoute
  AuthenticatedBibliotecaModelosRoute: typeof AuthenticatedBibliotecaModelosRouteWithChildren
  AuthenticatedConfiguracoesIaRoute: typeof AuthenticatedConfiguracoesIaRoute
  AuthenticatedConfiguracoesIdentidadeRoute: typeof AuthenticatedConfiguracoesIdentidadeRoute
  AuthenticatedConfiguracoesSegurancaRoute: typeof AuthenticatedConfiguracoesSegurancaRoute
  AuthenticatedFerramentasLinksRoute: typeof AuthenticatedFerramentasLinksRoute
  AuthenticatedPecasIdRoute: typeof AuthenticatedPecasIdRoute
  AuthenticatedPecasNovaRoute: typeof AuthenticatedPecasNovaRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAssistentesRoute: AuthenticatedAssistentesRoute,
  AuthenticatedBibliotecariosRoute: AuthenticatedBibliotecariosRoute,
  AuthenticatedCnjRoute: AuthenticatedCnjRoute,
  AuthenticatedCompartilhamentosRoute: AuthenticatedCompartilhamentosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoricoLoteRoute: AuthenticatedHistoricoLoteRoute,
  AuthenticatedJurisprudenciaRoute: AuthenticatedJurisprudenciaRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
  AuthenticatedAdminIntegracoesRoute: AuthenticatedAdminIntegracoesRoute,
  AuthenticatedBibliotecaModelosRoute:
    AuthenticatedBibliotecaModelosRouteWithChildren,
  AuthenticatedConfiguracoesIaRoute: AuthenticatedConfiguracoesIaRoute,
  AuthenticatedConfiguracoesIdentidadeRoute:
    AuthenticatedConfiguracoesIdentidadeRoute,
  AuthenticatedConfiguracoesSegurancaRoute:
    AuthenticatedConfiguracoesSegurancaRoute,
  AuthenticatedFerramentasLinksRoute: AuthenticatedFerramentasLinksRoute,
  AuthenticatedPecasIdRoute: AuthenticatedPecasIdRoute,
  AuthenticatedPecasNovaRoute: AuthenticatedPecasNovaRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PSlugRoute: PSlugRoute,
  ApiPublicAdvogaProcessContextRoute: ApiPublicAdvogaProcessContextRoute,
  ApiPublicInventariaProcessContextRoute:
    ApiPublicInventariaProcessContextRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
