// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const viteUrl = import.meta.env.VITE_SUPABASE_URL;
  const viteKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
  const procUrl = typeof process !== 'undefined' ? process.env?.SUPABASE_URL : undefined;
  const procKey = typeof process !== 'undefined' ? process.env?.SUPABASE_PUBLISHABLE_KEY : undefined;

  const SUPABASE_URL = viteUrl || procUrl;
  const SUPABASE_PUBLISHABLE_KEY = viteKey || procKey;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const isBrowser = typeof window !== 'undefined';
    const missing: string[] = [];
    if (!SUPABASE_URL) missing.push(isBrowser ? 'VITE_SUPABASE_URL' : 'SUPABASE_URL');
    if (!SUPABASE_PUBLISHABLE_KEY) missing.push(isBrowser ? 'VITE_SUPABASE_PUBLISHABLE_KEY' : 'SUPABASE_PUBLISHABLE_KEY');
    const hint = isBrowser
      ? 'The published bundle is missing build-time VITE_* envs. Republish the app from Lovable to rebuild with the current .env.'
      : 'Connect Supabase in Lovable Cloud.';
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. ${hint}`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

